WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
ERROR demo.py:14 error info
WARNING demo.py:15 warn info
INFO demo.py:16 info info
DEBUG demo.py:17 debug info
WARNING _internal.py:88  * Debugger is active!
ERROR demo.py:14 error info
WARNING demo.py:15 warn info
INFO demo.py:16 info info
DEBUG demo.py:17 debug info
WARNING _internal.py:88  * Debugger is active!
ERROR demo.py:14 error info
WARNING demo.py:15 warn info
INFO demo.py:16 info info
DEBUG demo.py:17 debug info
ERROR demo.py:14 error info
WARNING demo.py:15 warn info
INFO demo.py:16 info info
DEBUG demo.py:17 debug info
WARNING _internal.py:88  * Debugger is active!
ERROR demo.py:15 error info
WARNING demo.py:16 warn info
INFO demo.py:17 info info
DEBUG demo.py:18 debug info
ERROR demo.py:15 error info
WARNING demo.py:16 warn info
INFO demo.py:17 info info
DEBUG demo.py:18 debug info
ERROR demo.py:15 error info
WARNING demo.py:16 warn info
INFO demo.py:17 info info
DEBUG demo.py:18 debug info
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
ERROR demo.py:15 error info
WARNING demo.py:16 warn info
INFO demo.py:17 info info
DEBUG demo.py:18 debug info
ERROR __init__.py:97 Error: Path doesn't exist: 'migrations'.  Please use the 'init' command to create a new scripts folder.
ERROR __init__.py:97 Error: Path doesn't exist: 'migrations'.  Please use the 'init' command to create a new scripts folder.
ERROR __init__.py:97 Error: Path doesn't exist: 'migrations'.  Please use the 'init' command to create a new scripts folder.
WARNING _internal.py:88  * Debugger is active!
ERROR demo.py:14 error info
WARNING demo.py:15 warn info
INFO demo.py:16 info info
DEBUG demo.py:17 debug info
ERROR demo.py:14 error info
WARNING demo.py:15 warn info
INFO demo.py:16 info info
DEBUG demo.py:17 debug info
ERROR __init__.py:97 Error: Path doesn't exist: 'migrations'.  Please use the 'init' command to create a new scripts folder.
ERROR demo.py:14 error info
WARNING demo.py:15 warn info
ERROR demo.py:14 error info
WARNING demo.py:15 warn info
WARNING _internal.py:88  * Debugger is active!
ERROR demo.py:14 error info
WARNING demo.py:15 warn info
INFO demo.py:16 info info
DEBUG demo.py:17 debug info
ERROR __init__.py:97 Error: Path doesn't exist: 'migrations'.  Please use the 'init' command to create a new scripts folder.
ERROR __init__.py:97 Error: Path doesn't exist: 'migrations'.  Please use the 'init' command to create a new scripts folder.
ERROR __init__.py:97 Error: Path doesn't exist: 'migrations'.  Please use the 'init' command to create a new scripts folder.
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
ERROR verify_code.py:23 value is not an integer or out of range
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
2018-12-21 17:47:40,795 WARNING _internal.py:88  * Debugger is active!
2018-12-21 17:47:51,610 WARNING _internal.py:88  * Debugger is active!
2018-12-21 17:49:42,845 WARNING _internal.py:88  * Debugger is active!
2018-12-21 18:07:09,703 WARNING _internal.py:88  * Debugger is active!
2018-12-21 18:07:50,455 WARNING _internal.py:88  * Debugger is active!
2018-12-21 18:10:29,016 WARNING _internal.py:88  * Debugger is active!
2018-12-21 18:10:39,623 ERROR verify_code.py:55 'bytes' object has no attribute 'encode'
2018-12-21 18:11:24,768 WARNING _internal.py:88  * Debugger is active!
2018-12-21 18:11:29,468 ERROR verify_code.py:89 When initializing mapper Mapper|User|ih_user_profile, expression 'House' failed to locate a name ("name 'House' is not defined"). If this is a class name, consider adding this relationship() to the <class 'ihome.models.User'> class after both dependent classes have been defined.
2018-12-24 09:06:43,477 WARNING _internal.py:88  * Debugger is active!
2018-12-24 09:09:39,220 ERROR verify_code.py:89 When initializing mapper Mapper|User|ih_user_profile, expression 'House' failed to locate a name ("name 'House' is not defined"). If this is a class name, consider adding this relationship() to the <class 'ihome.models.User'> class after both dependent classes have been defined.
2018-12-24 09:32:53,689 WARNING _internal.py:88  * Debugger is active!
2018-12-24 09:33:05,264 WARNING _internal.py:88  * Debugger is active!
2018-12-24 10:14:17,189 WARNING _internal.py:88  * Debugger is active!
2018-12-24 10:43:03,546 WARNING _internal.py:88  * Debugger is active!
2018-12-24 10:47:19,222 WARNING _internal.py:88  * Debugger is active!
2018-12-24 10:49:35,679 ERROR verify_code.py:56 'NoneType' object has no attribute 'decode'
2018-12-24 10:51:15,190 WARNING _internal.py:88  * Debugger is active!
2018-12-24 10:51:25,542 WARNING _internal.py:88  * Debugger is active!
2018-12-24 10:55:14,205 WARNING _internal.py:88  * Debugger is active!
2018-12-24 11:02:16,241 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:13:03,603 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:14:43,186 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:14:57,421 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:15:25,880 ERROR verify_code.py:90 When initializing mapper Mapper|User|ih_user_profile, expression 'House' failed to locate a name ("name 'House' is not defined"). If this is a class name, consider adding this relationship() to the <class 'ihome.models.User'> class after both dependent classes have been defined.
2018-12-25 10:17:33,523 ERROR verify_code.py:90 One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper|User|ih_user_profile'. Original exception was: When initializing mapper Mapper|User|ih_user_profile, expression 'House' failed to locate a name ("name 'House' is not defined"). If this is a class name, consider adding this relationship() to the <class 'ihome.models.User'> class after both dependent classes have been defined.
2018-12-25 10:19:32,563 ERROR verify_code.py:90 One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper|User|ih_user_profile'. Original exception was: When initializing mapper Mapper|User|ih_user_profile, expression 'House' failed to locate a name ("name 'House' is not defined"). If this is a class name, consider adding this relationship() to the <class 'ihome.models.User'> class after both dependent classes have been defined.
2018-12-25 10:22:26,527 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:22:46,331 ERROR verify_code.py:90 When initializing mapper Mapper|User|ih_user_profile, expression 'House' failed to locate a name ("name 'House' is not defined"). If this is a class name, consider adding this relationship() to the <class 'ihome.models.User'> class after both dependent classes have been defined.
2018-12-25 10:25:22,186 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:25:35,540 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:25:44,623 ERROR verify_code.py:90 When initializing mapper Mapper|User|ih_user_profile, expression 'House' failed to locate a name ("name 'House' is not defined"). If this is a class name, consider adding this relationship() to the <class 'ihome.models.User'> class after both dependent classes have been defined.
2018-12-25 10:26:45,091 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:26:57,679 ERROR verify_code.py:90 When initializing mapper Mapper|User|ih_user_profile, expression 'House' failed to locate a name ("name 'House' is not defined"). If this is a class name, consider adding this relationship() to the <class 'ihome.models.User'> class after both dependent classes have been defined.
2018-12-25 10:28:02,534 ERROR verify_code.py:90 One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper|User|ih_user_profile'. Original exception was: When initializing mapper Mapper|User|ih_user_profile, expression 'House' failed to locate a name ("name 'House' is not defined"). If this is a class name, consider adding this relationship() to the <class 'ihome.models.User'> class after both dependent classes have been defined.
2018-12-25 10:28:56,084 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:28:59,117 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:29:18,865 ERROR verify_code.py:90 When initializing mapper Mapper|User|ih_user_profile, expression 'House' failed to locate a name ("name 'House' is not defined"). If this is a class name, consider adding this relationship() to the <class 'ihome.models.User'> class after both dependent classes have been defined.
2018-12-25 10:31:32,303 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:31:37,970 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:32:03,002 ERROR verify_code.py:90 When initializing mapper Mapper|User|ih_user_profile, expression 'House' failed to locate a name ("name 'House' is not defined"). If this is a class name, consider adding this relationship() to the <class 'ihome.models.User'> class after both dependent classes have been defined.
2018-12-25 10:40:49,828 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:40:53,573 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:41:10,389 ERROR verify_code.py:90 When initializing mapper Mapper|User|ih_user_profile, expression 'House' failed to locate a name ("name 'House' is not defined"). If this is a class name, consider adding this relationship() to the <class 'ihome.models.User'> class after both dependent classes have been defined.
2018-12-25 10:52:57,152 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:53:51,789 WARNING _internal.py:88  * Debugger is active!
2018-12-25 10:56:06,574 WARNING _internal.py:88  * Debugger is active!
2018-12-25 11:08:14,483 WARNING _internal.py:88  * Debugger is active!
2018-12-25 11:08:39,885 WARNING _internal.py:88  * Debugger is active!
2018-12-25 11:10:29,754 WARNING _internal.py:88  * Debugger is active!
2018-12-25 11:11:07,384 WARNING _internal.py:88  * Debugger is active!
2018-12-25 11:12:58,420 WARNING _internal.py:88  * Debugger is active!
2018-12-25 11:14:43,666 WARNING _internal.py:88  * Debugger is active!
2018-12-26 10:19:58,147 WARNING _internal.py:88  * Debugger is active!
2018-12-26 10:22:47,008 WARNING _internal.py:88  * Debugger is active!
2018-12-26 10:23:05,464 WARNING _internal.py:88  * Debugger is active!
2018-12-26 10:23:15,028 WARNING _internal.py:88  * Debugger is active!
2018-12-26 10:25:46,270 ERROR passport.py:122 (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([WinError 10061] ����Ŀ�����������ܾ����޷����ӡ�)") (Background on this error at: http://sqlalche.me/e/e3q8)
2018-12-27 08:53:37,022 WARNING _internal.py:88  * Debugger is active!
2018-12-27 10:00:10,840 WARNING _internal.py:88  * Debugger is active!
2018-12-27 10:39:32,765 WARNING _internal.py:88  * Debugger is active!
2018-12-27 10:40:39,583 WARNING _internal.py:88  * Debugger is active!
2018-12-27 10:40:44,941 WARNING _internal.py:88  * Debugger is active!
2018-12-27 11:01:30,705 WARNING _internal.py:88  * Debugger is active!
2018-12-27 11:09:41,437 WARNING _internal.py:88  * Debugger is active!
2018-12-27 11:10:12,699 WARNING _internal.py:88  * Debugger is active!
2018-12-27 11:15:36,724 WARNING _internal.py:88  * Debugger is active!
2018-12-27 12:21:52,307 WARNING _internal.py:88  * Debugger is active!
2018-12-27 12:23:49,279 WARNING _internal.py:88  * Debugger is active!
2018-12-27 12:38:19,033 WARNING _internal.py:88  * Debugger is active!
2018-12-27 12:40:00,615 WARNING _internal.py:88  * Debugger is active!
2018-12-27 12:40:39,420 WARNING _internal.py:88  * Debugger is active!
2018-12-27 12:43:13,196 WARNING _internal.py:88  * Debugger is active!
2018-12-27 12:43:45,825 WARNING _internal.py:88  * Debugger is active!
2018-12-27 12:47:37,029 WARNING _internal.py:88  * Debugger is active!
2018-12-27 12:47:43,074 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:02:15,460 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:06:09,730 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:09:22,597 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:10:55,732 ERROR profile.py:90 Entity '<class 'ihome.models.User'>' has no property 'avatar'
2018-12-27 16:12:43,354 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:12:47,388 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:22:33,254 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:37:50,656 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:41:46,145 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:41:55,343 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:42:07,979 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:42:57,629 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:43:01,057 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:43:47,176 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:44:20,643 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:50:36,577 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:50:46,934 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:51:14,664 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:52:43,263 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:53:01,657 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:53:53,502 WARNING _internal.py:88  * Debugger is active!
2018-12-27 16:53:58,115 WARNING _internal.py:88  * Debugger is active!
2018-12-28 09:24:06,080 WARNING _internal.py:88  * Debugger is active!
2018-12-28 09:30:46,321 WARNING _internal.py:88  * Debugger is active!
2018-12-28 09:59:54,800 WARNING _internal.py:88  * Debugger is active!
2018-12-28 10:10:08,781 WARNING _internal.py:88  * Debugger is active!
2018-12-28 10:11:45,861 WARNING _internal.py:88  * Debugger is active!
2018-12-28 10:13:25,128 WARNING _internal.py:88  * Debugger is active!
2018-12-28 10:19:09,920 WARNING _internal.py:88  * Debugger is active!
2018-12-28 10:19:14,674 WARNING _internal.py:88  * Debugger is active!
2018-12-28 10:19:35,700 WARNING _internal.py:88  * Debugger is active!
2018-12-28 10:20:46,780 WARNING _internal.py:88  * Debugger is active!
2018-12-28 10:20:52,513 WARNING _internal.py:88  * Debugger is active!
2018-12-28 10:25:00,525 WARNING _internal.py:88  * Debugger is active!
2018-12-28 10:44:09,541 WARNING _internal.py:88  * Debugger is active!
2018-12-28 16:39:24,421 WARNING _internal.py:88  * Debugger is active!
2018-12-28 16:54:44,216 WARNING _internal.py:88  * Debugger is active!
2018-12-28 16:55:46,104 WARNING _internal.py:88  * Debugger is active!
2018-12-28 16:55:47,519 INFO houses.py:24 hit redis area_info
2018-12-28 16:55:57,377 INFO houses.py:24 hit redis area_info
2018-12-28 16:56:57,726 WARNING _internal.py:88  * Debugger is active!
2018-12-28 16:56:59,641 INFO houses.py:24 hit redis area_info
2018-12-28 17:06:07,726 WARNING _internal.py:88  * Debugger is active!
2018-12-29 09:13:25,507 WARNING _internal.py:88  * Debugger is active!
2018-12-29 09:33:06,497 WARNING _internal.py:88  * Debugger is active!
2018-12-29 09:33:10,959 INFO houses.py:24 hit redis area_info
2018-12-29 09:34:05,426 INFO houses.py:24 hit redis area_info
2018-12-29 11:04:33,717 WARNING _internal.py:88  * Debugger is active!
2018-12-29 11:04:56,487 INFO houses.py:25 hit redis area_info
2018-12-29 11:10:42,597 INFO houses.py:25 hit redis area_info
2018-12-29 11:14:59,464 WARNING _internal.py:88  * Debugger is active!
2018-12-29 11:19:21,869 WARNING _internal.py:88  * Debugger is active!
2018-12-29 11:19:30,064 WARNING _internal.py:88  * Debugger is active!
2018-12-29 11:19:39,450 WARNING _internal.py:88  * Debugger is active!
2018-12-29 11:19:45,430 WARNING _internal.py:88  * Debugger is active!
2018-12-29 11:19:58,398 WARNING _internal.py:88  * Debugger is active!
2018-12-29 11:23:38,502 WARNING _internal.py:88  * Debugger is active!
2018-12-29 11:24:20,582 WARNING _internal.py:88  * Debugger is active!
2018-12-29 11:26:03,736 WARNING _internal.py:88  * Debugger is active!
2018-12-29 13:54:05,576 WARNING _internal.py:88  * Debugger is active!
2018-12-29 13:56:44,404 WARNING _internal.py:88  * Debugger is active!
2018-12-29 13:59:39,729 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:01:01,018 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:02:09,899 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:05:54,324 INFO houses.py:25 hit redis area_info
2018-12-29 14:10:49,851 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:17:37,970 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:17:43,673 INFO houses.py:25 hit redis area_info
2018-12-29 14:17:57,313 INFO houses.py:25 hit redis area_info
2018-12-29 14:18:44,163 INFO houses.py:25 hit redis area_info
2018-12-29 14:24:28,066 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:24:44,173 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:25:26,785 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:26:22,237 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:26:33,746 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:26:59,154 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:27:04,827 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:27:18,519 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:27:29,967 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:29:09,845 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:30:46,191 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:30:56,439 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:31:36,465 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:31:52,435 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:32:10,715 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:32:28,966 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:32:39,162 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:33:29,436 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:33:52,203 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:52:32,016 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:53:19,069 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:57:53,031 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:58:21,729 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:58:49,203 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:58:56,119 INFO houses.py:24 hit redis area_info
2018-12-29 14:59:13,311 WARNING _internal.py:88  * Debugger is active!
2018-12-29 14:59:14,792 INFO houses.py:24 hit redis area_info
2018-12-29 15:05:25,130 WARNING _internal.py:88  * Debugger is active!
2018-12-29 15:05:25,447 INFO houses.py:24 hit redis area_info
2018-12-29 15:07:56,006 WARNING _internal.py:88  * Debugger is active!
2018-12-29 15:16:24,362 INFO houses.py:24 hit redis area_info
2018-12-29 15:16:28,299 INFO houses.py:24 hit redis area_info
2018-12-29 15:17:46,532 INFO houses.py:24 hit redis area_info
2018-12-29 15:25:13,778 WARNING _internal.py:88  * Debugger is active!
2018-12-29 15:26:03,265 WARNING _internal.py:88  * Debugger is active!
2018-12-29 15:52:31,718 WARNING _internal.py:88  * Debugger is active!
2018-12-29 16:02:04,602 WARNING _internal.py:88  * Debugger is active!
